[package]
name = "athm"
version = "0.1.0"
edition = "2021"

[features]
default = ["rustcrypto"]
rustcrypto = ["p256", "elliptic-curve", "sha2", "group", "ff", "sec1", "rand", "hash2curve", "getrandom"]
boringssl = ["bssl-sys"]
test-vectors = ["hex", "serde", "serde_json"]

[dependencies]
p256 = { version = "0.14", features = ["arithmetic", "group-digest", "ecdsa"], optional = true }
elliptic-curve = { version = "0.14", features = ["arithmetic", "digest", "sec1"], optional = true }
subtle = "2.6.1"
sha2 = { version = "0.11", optional = true }
rand = { version = "0.10", features = ["std"], optional = true }
zeroize = { version = "1.7", features = ["derive"] }
group = { version = "0.14", optional = true }
ff = { version = "0.14", optional = true }
sec1 = { version = "0.8", features = ["point"], optional = true }
hash2curve = { version = "0.14", optional = true }
getrandom = { version = "0.4", features = ["sys_rng"], optional = true }
hex = { version = "0.4", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"]  }
serde_json = { version = "1.0", optional = true}
bssl-sys = { path = "boringssl/rust/bssl-sys", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
hex-literal = "0.4"

[[bench]]
name = "athm_benchmarks"
harness = false

[[bin]]
name = "generate-test-vectors"
required-features = ["test-vectors"]

[[bin]]
name = "check-test-vectors"
required-features = ["test-vectors"]
