package(
    default_visibility = ["//:__subpackages__"],
)

filegroup(
    name = "strong_rsa_example_keys",
    srcs = [
        "strong_rsa_modulus2048_example.binarypb",
        "strong_rsa_modulus2048_example_2.binarypb",
        "strong_rsa_modulus3072_example.binarypb",
        "strong_rsa_modulus4096_example.binarypb",
    ],
)
